### ISSUE TITLE
YamlDotNet.dll Missing?

### ISSUE THREAD

**Issue by gazataeon** [Badgerati/Parcel#1]
### Expected Behaviour
Imported module!

### Actual Behaviour 

`Exception calling "LoadFrom" with "1" argument(s): "Could not load file or assembly '..badgerati\Parcel\src\lib\YamlDotNet\netstandard2.1\YamlDotNet.dll'. The system cannot find the file specified."
`

### Steps to reproduce
`Import-Module ./src/Parcel.psd1 -Force`
Windows 10 - Pwsh 6.2.3
MacOS - pwsh 6.2.0

**Comment by Badgerati** [comment]
Should be fixed now!
